---
- name: Install CRI-O on Ubuntu RPi
  hosts: all
  become: yes

  vars:
    # Set the CRI-O version to match your Kubernetes version
    crio_version: "v1.34"
    kubernetes_version: "v1.34"
    
  tasks:
    - name: Enable systemd-resolved search domains (option 119)
      lineinfile:
        insertafter: "[DHCPv4]"
        regexp: "^#UseDomains=.*$"
        line: UseDomains=yes


    - name: Disable SSHD UseDNS
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#UseDNS.*$'
        line: UseDNS no

    - name: Remove swap from fstab
      lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent

#  For RPi OS
#    - name: Disable rpi-swap
#      lineinfile:
#        path: /etc/rpi/swap.conf
#        regexp: '#Mechanism.*'
#        line: Mechanism=none


#  RPi OS has /boot/firmware/cmdline.txt
    - name: enable rpi cgroups
      lineinfile:
        path: /boot/firmware/current/cmdline.txt
        regexp: '^(.*)(?<!cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1)$'
        line: \1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1
        backrefs: true
        state: present
        create: true

    - name: Load overlay module
      modprobe:
        name: overlay
        persistent: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        persistent: present

    - name: Set ip_forward persistence
      lineinfile: 
        path: /etc/sysctl.d/k8s.conf
        line: net.ipv4.ip_forward = 1
        state: present
        create: true

    - name: Set bridge-nf-call-iptables persistence
      lineinfile: 
        path: /etc/sysctl.d/k8s.conf
        line: net.bridge.bridge-nf-call-iptables = 1
        state: present
        create: true

    - name: Set bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Set ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Update apt cache
      register: apt_updated
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: full

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - vim
          - curl
          - gnupg
          - lsb-release
          - python3-kubernetes
        state: present

    - name: Reboot after upgrade
      reboot:
        msg: "Rebooting after upgrade"
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 45 
        test_command: whoami
      when: apt_updated.changed


    - name: Add CRI-O GPG key
      ansible.builtin.get_url: 
        url: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/deb/Release.key
        dest: /etc/apt/keyrings/cri-o.asc
        mode: '0644'
        force: true

    - name: Add CRI-O repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/cri-o.asc] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/deb/ /'

    - name: Add Kubernetes GPG key
      ansible.builtin.get_url: 
        url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes.asc
        mode: '0644'
        force: true

    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /'

    - name: Update apt cache again
      apt:
        update_cache: yes

    - name: Install CRI-O and Kubernetes
      apt:
        name: 
          - cri-o
          - kubelet
          - kubeadm
          - kubectl
        state: present


    - name: Hold Kubernetes packages to prevent auto-updates (optional)
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable and start CRI-O service
      systemd:
        name: crio
        enabled: yes
        state: started
        daemon_reload: yes
      register: crio_status

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started
        daemon_reload: yes
      register: kubelet_status
